[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "python-parallel-computing-cookbook-notebook"
authors = [{name = "Jialin Yi", email = "jialinyi@sas.upenn.edu"}]
dynamic = ["version", "description"]
